version: '3.0'
services:
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: shippy
      MYSQL_USER: shippy
      MYSQL_PASSWORD: getitdone
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./.data:/var/lib/mysql

  redis:
    image: redis:4.0.5-alpine
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./.redis:/data

  enrollment:
    container_name: 'enrollment'
    build:
      context: ./enrollment
    volumes:
      - ./enrollment/src/:/app/src/
      - ./enrollment/tests/:/app/tests/
    environment:
      - MYSQL_HOST=mysql
      - PORT=3001
      - DEBUG=app:*
    ports:
      - "3001:3001"
    depends_on:
      - mysql

  # client:
  #   container_name: 'client'
  #   build:
  #     context: ./client
  #   volumes:
  #     - ./client/src/:/app/src/
  #     - ./cliient/tests/:/app/tests/
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - enrollment