version: '3.0'
services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: shippy
      MYSQL_USER: shippy
      MYSQL_PASSWORD: getitdone
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./.data:/var/lib/mysql

  redis:
    image: redis:4.0.5-alpine
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./.redis:/data