## Enrollment [/enroll]

### Enroll or update a seller [POST]

A "crupdate" POST which allows enrollment or unenrollment epending on isEnrolled attribute.
Returns 404 if either field is not provided.

+ Request

    + Headers

              Content-Type: application/json

    + Body


            {
                "sellerUsername": "coolguy123",
                "isEnrolled": true
            }


    + Schema

            <!-- include(../enrollment/src/schema/enrollment.post.schema.json) -->


+ Response 200 (application/json)


        {
            "sellerUsername": "coolguy123",
            "isEnrolled": true
        }


+ Response 400


## Enrollment status [/enroll/status/{sellerUsername}]

Returns the enrollment status of seller

+ Parameters

    + sellerUsername: coolguy123 (string) seller username to check for enrollment

### Get  [GET]

+ Response 200 (application/json)

        {
           {
            isEnrolled: false
           }
        }
